-- Add Tennis (Boys) fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'tennis-boys'), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-boys')), (SELECT id FROM teams WHERE name = 'AMITY' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-boys')), '2026-02-19', '12:00:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'tennis-boys'), (SELECT id FROM teams WHERE name = 'BENNETT' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-boys')), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-boys')), '2026-02-19', '15:00:00', 'upcoming', 'Group', NULL);

-- Add Tennis (Girls) fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'tennis-girls'), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-girls')), (SELECT id FROM teams WHERE name = 'BMU' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-girls')), '2026-02-19', '12:30:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'tennis-girls'), (SELECT id FROM teams WHERE name = 'HANSRAJ' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-girls')), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-girls')), '2026-02-19', '16:00:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'tennis-girls'), (SELECT id FROM teams WHERE name = 'HANSRAJ' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-girls')), (SELECT id FROM teams WHERE name = 'BMU' AND sport_id = (SELECT id FROM sports WHERE slug = 'tennis-girls')), '2026-02-19', '17:00:00', 'upcoming', 'Group', NULL);

-- Add Table Tennis (Boys) fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'table-tennis-boys'), (SELECT id FROM teams WHERE name = 'DTU' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), '2026-02-19', '12:30:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'table-tennis-boys'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), (SELECT id FROM teams WHERE name = 'ABES' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), '2026-02-19', '12:30:00', 'upcoming', 'Group', 'Pool B'),
((SELECT id FROM sports WHERE slug = 'table-tennis-boys'), (SELECT id FROM teams WHERE name = 'BMU' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), (SELECT id FROM teams WHERE name = 'GURU GOBIND' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), '2026-02-19', '13:00:00', 'upcoming', 'Group', 'Pool C'),
((SELECT id FROM sports WHERE slug = 'table-tennis-boys'), (SELECT id FROM teams WHERE name = 'BENNETT B' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), (SELECT id FROM teams WHERE name = 'IMI' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), '2026-02-19', '13:00:00', 'upcoming', 'Group', 'Pool D'),
((SELECT id FROM sports WHERE slug = 'table-tennis-boys'), (SELECT id FROM teams WHERE name = 'DTU' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), (SELECT id FROM teams WHERE name = 'HANSRAJ' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), '2026-02-19', '15:00:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'table-tennis-boys'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), (SELECT id FROM teams WHERE name = 'SRM' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-boys')), '2026-02-19', '15:30:00', 'upcoming', 'Group', 'Pool B');

-- Add Table Tennis (Girls) fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'table-tennis-girls'), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-girls')), (SELECT id FROM teams WHERE name = 'BMU' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-girls')), '2026-02-19', '12:30:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'table-tennis-girls'), (SELECT id FROM teams WHERE name = 'HANSRAJ' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-girls')), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-girls')), '2026-02-19', '16:00:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'table-tennis-girls'), (SELECT id FROM teams WHERE name = 'HANSRAJ' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-girls')), (SELECT id FROM teams WHERE name = 'BMU' AND sport_id = (SELECT id FROM sports WHERE slug = 'table-tennis-girls')), '2026-02-19', '17:00:00', 'upcoming', 'Group', 'Pool A');

-- Add Basketball (Boys) fixtures - Pool C - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'basketball-boys'), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), (SELECT id FROM teams WHERE name = 'MOTILAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), '2026-02-19', '08:00:00', 'upcoming', 'Group', 'Pool C'),
((SELECT id FROM sports WHERE slug = 'basketball-boys'), (SELECT id FROM teams WHERE name = 'SNU' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), (SELECT id FROM teams WHERE name = 'JIIT' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), '2026-02-19', '10:00:00', 'upcoming', 'Group', 'Pool C'),
((SELECT id FROM sports WHERE slug = 'basketball-boys'), (SELECT id FROM teams WHERE name = 'MOTILAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), (SELECT id FROM teams WHERE name = 'SNU' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), '2026-02-19', '12:00:00', 'upcoming', 'Group', 'Pool C'),
((SELECT id FROM sports WHERE slug = 'basketball-boys'), (SELECT id FROM teams WHERE name = 'OP JINDAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), (SELECT id FROM teams WHERE name = 'JIIT' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), '2026-02-19', '14:00:00', 'upcoming', 'Group', 'Pool C');

-- Add Basketball (Boys) fixtures - Pool D - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'basketball-boys'), (SELECT id FROM teams WHERE name = 'BENNETT' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), (SELECT id FROM teams WHERE name = 'ASHOKA' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), '2026-02-19', '08:00:00', 'upcoming', 'Group', 'Pool D'),
((SELECT id FROM sports WHERE slug = 'basketball-boys'), (SELECT id FROM teams WHERE name = 'SRM' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), (SELECT id FROM teams WHERE name = 'BENNETT' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), '2026-02-19', '10:00:00', 'upcoming', 'Group', 'Pool D'),
((SELECT id FROM sports WHERE slug = 'basketball-boys'), (SELECT id FROM teams WHERE name = 'ASHOKA' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), (SELECT id FROM teams WHERE name = 'SRM' AND sport_id = (SELECT id FROM sports WHERE slug = 'basketball-boys')), '2026-02-19', '12:00:00', 'upcoming', 'Group', 'Pool D');

-- Add Volleyball (Boys) fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'volleyball-boys'), (SELECT id FROM teams WHERE name = 'KUMAUN' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), (SELECT id FROM teams WHERE name = 'BENNETT B' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), '2026-02-19', '14:00:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'volleyball-boys'), (SELECT id FROM teams WHERE name = 'IILM' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), (SELECT id FROM teams WHERE name = 'GL BAJAJ' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), '2026-02-19', '15:00:00', 'upcoming', 'Group', 'Pool B'),
((SELECT id FROM sports WHERE slug = 'volleyball-boys'), (SELECT id FROM teams WHERE name = 'MANAV R' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), (SELECT id FROM teams WHERE name = 'KUMAUN' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), '2026-02-19', '16:00:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'volleyball-boys'), (SELECT id FROM teams WHERE name = 'NIU' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), (SELECT id FROM teams WHERE name = 'BENNETT B' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), '2026-02-19', '17:00:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'volleyball-boys'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), (SELECT id FROM teams WHERE name = 'IILM' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), '2026-02-19', '18:00:00', 'upcoming', 'Group', 'Pool B'),
((SELECT id FROM sports WHERE slug = 'volleyball-boys'), (SELECT id FROM teams WHERE name = 'MANAV R' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), (SELECT id FROM teams WHERE name = 'SHARDA' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), '2026-02-19', '19:00:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'volleyball-boys'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), (SELECT id FROM teams WHERE name = 'PGDAV' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-boys')), '2026-02-19', '20:00:00', 'upcoming', 'Group', 'Pool B');

-- Add Volleyball (Girls) fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'volleyball-girls'), (SELECT id FROM teams WHERE name = 'ASHOKA' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), (SELECT id FROM teams WHERE name = 'KUMAON' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), '2026-02-19', '12:00:00', 'upcoming', 'Group', 'Pool B'),
((SELECT id FROM sports WHERE slug = 'volleyball-girls'), (SELECT id FROM teams WHERE name = 'MODY' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), (SELECT id FROM teams WHERE name = 'SRM' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), '2026-02-19', '13:30:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'volleyball-girls'), (SELECT id FROM teams WHERE name = 'BENNETT B' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), (SELECT id FROM teams WHERE name = 'KUMAON' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), '2026-02-19', '14:30:00', 'upcoming', 'Group', 'Pool B'),
((SELECT id FROM sports WHERE slug = 'volleyball-girls'), (SELECT id FROM teams WHERE name = 'IILM' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), (SELECT id FROM teams WHERE name = 'MODY' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), '2026-02-19', '16:00:00', 'upcoming', 'Group', 'Pool A'),
((SELECT id FROM sports WHERE slug = 'volleyball-girls'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), (SELECT id FROM teams WHERE name = 'IILM' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), '2026-02-19', '17:30:00', 'upcoming', 'Group', 'Pool B'),
((SELECT id FROM sports WHERE slug = 'volleyball-girls'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), (SELECT id FROM teams WHERE name = 'SRM' AND sport_id = (SELECT id FROM sports WHERE slug = 'volleyball-girls')), '2026-02-19', '19:30:00', 'upcoming', 'Group', 'Pool A');

-- Add Kabaddi fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'kabaddi'), (SELECT id FROM teams WHERE name = 'ZHDC' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), (SELECT id FROM teams WHERE name = 'SHARDA' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), '2026-02-19', '12:00:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'kabaddi'), (SELECT id FROM teams WHERE name = 'BENNETT B' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), (SELECT id FROM teams WHERE name = 'NIU' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), '2026-02-19', '12:40:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'kabaddi'), (SELECT id FROM teams WHERE name = 'SHARDA' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), (SELECT id FROM teams WHERE name = 'BML' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), '2026-02-19', '13:20:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'kabaddi'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), (SELECT id FROM teams WHERE name = 'ZHDC' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), '2026-02-19', '14:00:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'kabaddi'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), (SELECT id FROM teams WHERE name = 'BML' AND sport_id = (SELECT id FROM sports WHERE slug = 'kabaddi')), '2026-02-19', '15:10:00', 'upcoming', 'Group', NULL);

-- Add Football fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'football'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'football')), (SELECT id FROM teams WHERE name = 'MIU' AND sport_id = (SELECT id FROM sports WHERE slug = 'football')), '2026-02-19', '16:00:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'football'), (SELECT id FROM teams WHERE name = 'GALGOTIA' AND sport_id = (SELECT id FROM sports WHERE slug = 'football')), (SELECT id FROM teams WHERE name = 'DOON GLOBAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'football')), '2026-02-19', '17:30:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'football'), (SELECT id FROM teams WHERE name = 'BENNETT A' AND sport_id = (SELECT id FROM sports WHERE slug = 'football')), (SELECT id FROM teams WHERE name = 'SHARDA' AND sport_id = (SELECT id FROM sports WHERE slug = 'football')), '2026-02-19', '19:00:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'football'), (SELECT id FROM teams WHERE name = 'BENNETT B' AND sport_id = (SELECT id FROM sports WHERE slug = 'football')), (SELECT id FROM teams WHERE name = 'ALUMNI' AND sport_id = (SELECT id FROM sports WHERE slug = 'football')), '2026-02-19', '21:00:00', 'upcoming', 'Group', NULL);

-- Add Cricket fixtures - Day 1 (19-2-2026)
INSERT INTO fixtures (sport_id, team_a_id, team_b_id, match_date, match_time, status, round, pool) VALUES
((SELECT id FROM sports WHERE slug = 'cricket'), (SELECT id FROM teams WHERE name = 'SNU' AND sport_id = (SELECT id FROM sports WHERE slug = 'cricket')), (SELECT id FROM teams WHERE name = 'IILM' AND sport_id = (SELECT id FROM sports WHERE slug = 'cricket')), '2026-02-19', '07:30:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'cricket'), (SELECT id FROM teams WHERE name = 'UPES' AND sport_id = (SELECT id FROM sports WHERE slug = 'cricket')), (SELECT id FROM teams WHERE name = 'SRM' AND sport_id = (SELECT id FROM sports WHERE slug = 'cricket')), '2026-02-19', '11:30:00', 'upcoming', 'Group', NULL),
((SELECT id FROM sports WHERE slug = 'cricket'), (SELECT id FROM teams WHERE name = 'VENKY' AND sport_id = (SELECT id FROM sports WHERE slug = 'cricket')), (SELECT id FROM teams WHERE name = 'MANIPAL' AND sport_id = (SELECT id FROM sports WHERE slug = 'cricket')), '2026-02-19', '13:30:00', 'upcoming', 'Group', NULL);
